"root"
{
	"box_boss_keymaster_items"
	{
		"type" 		"garant_list"
		"chance"	"100"
		
		"items"
		{
			"item_enigmatic_fire"	"100"
			"item_boss_soul" 		"2"
		}
	}
	
	"box_boss_keymaster"
	{
		"type"		"uniform_list"
		
		"chance"	"100"
	
		"items"
		{
			"item_shard_hola"		"1"
			"item_shard_joe_black"	"1"
			"item_shard_satan"		"1"
			"item_shard_huntress"	"1"
		}
		
		"childs"
		{
			"box_boss_keymaster_items" "1"
		}
	}
	
	"box_boss_soul_guradian"
	{
		"type"		"garant_list"
		
		"items"
		{
			"item_boss_soul" 		"1"
		}
	}

	"box_boss_possessed"
	{
		"type"		"garant_list"
		
		"items"
		{
			"item_possessed_sword"	"1"
			"item_boss_soul"		"1"
		}
	}
	
	"box_boss_abyss_warrior"
	{
		"type"		"garant_list"
		
		"items"
		{
			"item_boss_soul"		"1"
			"item_aegis_aa"			"1"
		}
	}

	"box_neutral_items_tier1"
	{
		"type"		"uniform_list"
			
		"chance"	"35"
		
		"items"
		{
			"item_keen_optic"				  "1"
			"item_trusty_shovel"			  "1"
			"item_arcane_ring"				  "1"			
			"item_possessed_mask"			  "1"
			"item_mysterious_hat"			  "1"
			"item_unstable_wand"			  "1"
			"item_pogo_stick"				  "1"							
			"item_safety_bubble"			  "1"
			"item_seeds_of_serenity"		  "1"
			"item_lance_of_pursuit"			  "1"
			"item_occult_bracelet"			  "1"
			"item_duelist_gloves"			  "1"
			"item_ocean_heart"				  "1"
			"item_broom_handle"				  "1"
			"item_chipped_vest"				  "1"
			"item_royal_jelly"				  "1"
			"item_faded_broach"				  "1"
			"item_ironwood_tree"			  "1"
			"item_spark_of_courage"			  "1"
			"item_dust"				 			  "1"
			"item_smoke_of_deceit"				  "1"
            "item_enchanted_mango"				  "1"
            "item_flask"						  "1"
            "item_wraith_band" 					  "1"
            "item_null_talisman" 				  "1"
            "item_bracer" 						  "1"
		}
	}
	
	"box_neutral_items_tier2"
	{
		"type"		"uniform_list"
			
		"chance"	"35"

		"items"
		{
			"item_ring_of_aquila"			  "1"
			"item_imp_claw"					  "1"
			"item_nether_shawl"				  "1"
			"item_dragon_scale"				  "1"
			"item_whisper_of_the_dread"				  "1"
			"item_pupils_gift"				  "1"
			"item_vambrace"			  "1"
			"item_misericorde"				  "1"
			"item_grove_bow"				  "1"
			"item_philosophers_stone"				  "1"
			"item_essence_ring"				  "1"
			"item_paintball"				"1"
			"item_bullwhip"			  "1"
			"item_quicksilver_amulet"				  "1"
			"item_dagger_of_ristul"			"1"
			"item_orb_of_destruction"		  "1"
			"item_specialists_array"			"1"
			"item_eye_of_the_vizier"				  "1"
			"item_vampire_fangs"				  "1"
			"item_blighted_spirit"				  "1"
			"item_gossamer_cape"				  "1"
			"item_light_collector"				"1"
			"item_boots"				  "1"
			"item_gloves"			  "1"
			"item_belt_of_strength"			  "1"
			"item_robe"				  "1"
			"item_boots_of_elves"					  "1"
			"item_chainmail"		  "1"
			"item_bottle"				  "1"
			"item_ogre_axe" "1"
			"item_blade_of_alacrity" "1"
			"item_staff_of_wizardry" "1"
		}
	}
	
	"box_neutral_items_tier3"
	{
		"type"		"uniform_list"
	
		"chance"	"30"
		
		"items"
		{		
			"item_quickening_charm"			  "1"
			"item_defiant_shell"			  "1"
			"item_black_powder_bag"				  "1"
			"item_spider_legs"				  "1"
			"item_icarus_wings"					"1"
			"item_paladin_sword"			  "1"
			"item_nemesis_curse"			  "1"
			"item_vindicators_axe"			  "1"
			"item_dandelion_amulet"			  "1"
			"item_orb_of_destruction"		  "1"
			"item_titan_sliver"				  "1"
			"item_craggy_coat"					"1"
			"item_enchanted_quiver"				  "1"
			"item_elven_tunic"				  	"1"
			"item_cloak_of_flames"				"1"
			"item_ceremonial_robe"				"1"
			"item_psychic_headband"				"1"
			"item_slime_vial"					"1"
			"item_ogre_seal_totem"					"1"
			"item_doubloon"					"1"
			"item_power_treads"				  "1"
			"item_phase_boots"		  "1"
			"item_arcane_boots"			  "1"
			"item_medallion_of_courage"				  "1"
			"item_soul_ring"				  "1"
			"item_vanguard"				  "1"
			"item_tome_un_3" "1"
			"item_tome_med" "1"
			"item_tome_str_3" "1"
			"item_tome_int_3" "1"
			"item_tome_agi_3" "1"
		}
	}
	
	"box_neutral_items_tier4"
	{
		"type"		"uniform_list"
	
		"chance"	"30"
		
		"items"
		{	
			"item_timeless_relic"			  "1"
			"item_spell_prism"				  "1"
			"item_ascetic_cap"				  "1"
			"item_avianas_feather"				  "1"			
			"item_heavy_blade"				  "1"
			"item_flicker"					  "1"
			"item_ninja_gear"				  "1"
			"item_illusionsts_cape"		  "1"
			"item_fortitude_ring"			  "1"
			"item_the_leveller"				  "1"
			"item_minotaur_horn"			  "1"
			"item_spy_gadget"				  "1"
			"item_trickster_cloak"			  "1"
			"item_stormcrafter"			  "1"
			"item_penta_edged_sword"		  "1"
			"item_ancient_guardian"		  "1"
			"item_havoc_hammer"				"1"			
			"item_princes_knife"			"1"
			"item_barricade"			  	  "1"			
			"item_horizons_equilibrium"			  "1"
			"item_mind_breaker"				  "1"
			"item_martyrs_plate"			  "1"
			"item_rattlecage"				"1"
			"item_solar_crest"			  "1"
			"item_sange"			  "1"
			"item_yasha"				  "1"
			"item_tome_str_6"				  "1"
			"item_tome_int_6"				  "1"
			"item_tome_agi_6"				  "1"
			"item_tome_un_6" "1"
		}
	}
	"box_neutral_items_tier5"
	{
		"type"		"uniform_list"
	
		"chance"	"10"
		
		"items"
		{
			"item_force_boots"				  "1"
			"item_seer_stone"				  "1"
			"item_mirror_shield"			  	  "1"
			"item_apex"					  "1"
			"item_ballista"					  "1"
			"item_demonicon"				  "1"
			"item_fallen_sky"		  	  "1"
			"item_force_field"				  "1"
			"item_pirate_hat"				  "1"
			"item_ex_machina"				  "1"
			"item_giants_ring"				  "1"
			"item_unwavering_condition"				  "1"
			"item_vengeances_shadow"				  "1"
			"item_book_of_shadows"			  "1"
		}
	}
}
