item_amaliels_cuirass = item_amaliels_cuirass or class({})

LinkLuaModifier("modifier_amaliels_cuirass_passive", "items/amaliels_cuirass/modifiers/modifier_amaliels_cuirass_passive", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_amaliels_cuirass_aura_friend", "items/amaliels_cuirass/modifiers/modifier_amaliels_cuirass_passive", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_amaliels_cuirass_aura_friend_buff", "items/amaliels_cuirass/modifiers/modifier_amaliels_cuirass_passive", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_amaliels_cuirass_aura_enemy", "items/amaliels_cuirass/modifiers/modifier_amaliels_cuirass_passive", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_amaliels_cuirass_aura_enemy_debuff", "items/amaliels_cuirass/modifiers/modifier_amaliels_cuirass_passive", LUA_MODIFIER_MOTION_NONE)

function item_amaliels_cuirass:GetIntrinsicModifierName()
	return "modifier_amaliels_cuirass_passive"
end
