"boss_spawners"
{
    "target_mark_boss_easy_radiant_1"
    {
        "type" "npc_monk_of_love"
    }

    "target_mark_boss_easy_radiant_2"
    {
        "type" "npc_monk_of_love"
    }

    "target_mark_boss_medium_radiant_1"
    {
        "type" "npc_angel_of_love"
    }

    "target_mark_boss_medium_radiant_2"
    {
        "type" "npc_angel_of_love"
    }

    "target_mark_boss_easy_dire_1"
    {
        "type" "npc_monk_of_hate"
    }

    "target_mark_boss_easy_dire_2"
    {
        "type" "npc_monk_of_hate"
    }

    "target_mark_boss_medium_dire_1"
    {
        "type" "npc_angel_of_hate"
    }

    "target_mark_boss_medium_dire_2"
    {
        "type" "npc_angel_of_hate"
    }

    "target_mark_boss_omniknight"
    {
        "type" "npc_dota_custom_guardian"
    }

    "target_mark_boss_satan"
    {
        "type" "Demon_possessed"
    }

    "target_mark_boss_crazy"
    {
        "type" "npc_boss_travaler"
    }
}
