"root"
{
	"base_stats"
	{
		"1"
		{		
			"drops"
			{
				"box_neutral_items_tier1" 	"100"
			}
		}
		"5"
		{
			"drops"
			{
				"box_neutral_items_tier1" 	"100"
			}
		}

		"10"
		{
			"drops"
			{
				"box_neutral_items_tier1" 	"100"
			}
		}

		"15"
		{	
			"drops"
			{
				"box_neutral_items_tier2" 	"100"
			}
		}

		"20"
		{
			"drops"
			{
				"box_neutral_items_tier2" 	"100"
			}
		}

		"25"
		{
			"drops"
			{
				"box_neutral_items_tier2" 	"100"
			}
		}

		"40"
		{		
			"drops"
			{
				"box_neutral_items_tier3" 	"100"
			}
		}

		"60"
		{
			"drops"
			{
				"box_neutral_items_tier4" 	"100"
			}
		}

		"80"
		{
			"drops"
			{
				"box_neutral_items_tier4" 	"100"
			}
		}

		"100"
		{
			"drops"
			{
				"box_neutral_items_tier4" 	"100"
			}
		}
	}
	
	"stats"
	{
		"normal"
		{
			"1"
			{
				"hero_avg_level"	"1"
				
				"hp"		"500"
				"mp"		"500"
				"armor"		"1"
				"dmg_min"	"31"
				"dmg_max"	"35"
				"bat"		"1.1"
				"exp"		"67"
				"gold_min"	"25"
				"gold_max"	"31"
				"model_scale" "0.7"
			}

			"5"
			{
				"hero_avg_level"	"4"
				
				"hp"		"750"
				"mp"		"500"
				"armor"		"3"
				"dmg_min"	"54"
				"dmg_max"	"58"
				"bat"		"1.1"
				"exp"		"70"
				"gold_min"	"35"
				"gold_max"	"55"
				"model_scale" "0.75"
			}

			"10"
			{
				"hero_avg_level"	"8"
				
				"hp"		"1000"
				"mp"		"500"
				"armor"		"4"
				"dmg_min"	"81"
				"dmg_max"	"85"
				"bat"		"1.1"
				"exp"		"80"
				"gold_min"	"60"
				"gold_max"	"85"
				"model_scale" "0.8"
			}

			"15"
			{	
				"hero_avg_level"	"10"
				
				"hp"		"2000"
				"mp"		"500"
				"armor"		"5"
				"dmg_min"	"240"
				"dmg_max"	"260"
				"bat"		"1.0"
				"exp"		"100"
				"gold_min"	"90"
				"gold_max"	"120"
				"model_scale" "0.85"
			}

			"20"
			{
				"hero_avg_level"	"15"
				
				"hp"		"3000"
				"mp"		"500"
				"armor"		"6"
				"dmg_min"	"300"
				"dmg_max"	"320"
				"bat"		"1.0"
				"exp"		"120"
				"gold_min"	"100"
				"gold_max"	"144"
				"model_scale" "0.9"
			}

			"25"
			{
				"hero_avg_level"	"20"
				
				"hp"		"4000"
				"mp"		"500"
				"armor"		"7"
				"dmg_min"	"320"
				"dmg_max"	"340"
				"bat"		"1.0"
				"exp"		"180"
				"gold_min"	"110"
				"gold_max"	"151"
				"model_scale" "1"
			}

			"40"
			{
				"hero_avg_level"	"35"
				
				"hp"		"5000"
				"mp"		"500"
				"armor"		"9"
				"dmg_min"	"420"
				"dmg_max"	"460"
				"bat"		"0.7"
				"exp"		"220"
				"gold_min"	"250"
				"gold_max"	"350"
				"model_scale" "1.1"
			}

			"60"
			{
				"hero_avg_level"	"50"
				
				"hp"		"6000"
				"mp"		"500"
				"armor"		"14"
				"dmg_min"	"580"
				"dmg_max"	"640"
				"bat"		"0.6"
				"exp"		"260"
				"gold_min"	"300"
				"gold_max"	"450"
				"model_scale" "1.2"
			}

			"80"
			{
				"hero_avg_level"	"60"
				
				"hp"		"7000"
				"mp"		"500"
				"armor"		"16"
				"dmg_min"	"830"
				"dmg_max"	"880"
				"bat"		"0.6"
				"exp"		"300"
				"gold_min"	"350"
				"gold_max"	"500"
				"model_scale" "1.3"
			}

			"100"
			{
				"hero_avg_level"	"70"
				
				"hp"		"8000"
				"mp"		"500"
				"armor"		"18"
				"dmg_min"	"1100"
				"dmg_max"	"1200"
				"bat"		"0.2"
				"exp"		"340"
				"gold_min"	"400"
				"gold_max"	"550"
				"model_scale" "1.4"
			}
		}

		// ---------------------------------------------------
		
		"ancient"
		{
			"1"
			{
				"hero_avg_level"	"-100"
				
				"hp"		"750"
				"mp"		"1000"
				"armor"		"2"
				"dmg_min"	"53"
				"dmg_max"	"57"
				"bat"		"1.0"
				"exp"		"80"
				"gold_min"	"50"
				"gold_max"	"65"
				"model_scale" "0.7"
			}

			"5"
			{
				"hero_avg_level"	"4"
				
				"hp"		"1000"
				"mp"		"1000"
				"armor"		"5"
				"dmg_min"	"83"
				"dmg_max"	"87"
				"bat"		"1.0"
				"exp"		"120"
				"gold_min"	"70"
				"gold_max"	"85"
				"model_scale" "0.75"
			}

			"10"
			{
				"hero_avg_level"	"8"
				
				"hp"		"1500"
				"mp"		"1000"
				"armor"		"6"
				"dmg_min"	"118"
				"dmg_max"	"122"
				"bat"		"1.0"
				"exp"		"160"
				"gold_min"	"90"
				"gold_max"	"115"
				"model_scale" "0.8"
			}

			"15"
			{
				"hero_avg_level"	"10"
				
				"hp"		"1800"
				"mp"		"1000"
				"armor"		"7"
				"dmg_min"	"265"
				"dmg_max"	"290"
				"bat"		"1.0"
				"exp"		"200"
				"gold_min"	"120"
				"gold_max"	"135"
				"model_scale" "0.85"
			}

			"20"
			{
				"hero_avg_level"	"15"
				
				"hp"		"3000"
				"mp"		"1000"
				"armor"		"8"
				"dmg_min"	"300"
				"dmg_max"	"320"
				"bat"		"1.0"
				"exp"		"240"
				"gold_min"	"120"
				"gold_max"	"150"
				"model_scale" "0.9"
			}


			"25"
			{
				"hero_avg_level"	"20"
				
				"hp"		"4000"
				"mp"		"1000"
				"armor"		"9"
				"dmg_min"	"350"
				"dmg_max"	"380"
				"bat"		"0.9"
				"exp"		"280"
				"gold_min"	"160"
				"gold_max"	"180"
				"model_scale" "1"
			}

			"40"
			{
				"hero_avg_level"	"35"
				
				"hp"		"5000"
				"mp"		"1000"
				"armor"		"18"
				"dmg_min"	"520"
				"dmg_max"	"580"
				"bat"		"0.6"
				"exp"		"320"
				"gold_min"	"200"
				"gold_max"	"250"
				"model_scale" "1.1"
			}

			"60"
			{
				"hero_avg_level"	"50"
				
				"hp"		"6000"
				"mp"		"1000"
				"armor"		"20"
				"dmg_min"	"750"
				"dmg_max"	"820"
				"bat"		"0.5"
				"exp"		"360"
				"gold_min"	"300"
				"gold_max"	"350"
				"model_scale" "1.2"
			}

			"80"
			{
				"hero_avg_level"	"60"
				
				"hp"		"7000"
				"mp"		"1000"
				"armor"		"18"
				"dmg_min"	"1020"
				"dmg_max"	"1060"
				"bat"		"0.4"
				"exp"		"400"
				"gold_min"	"400"
				"gold_max"	"550"
				"model_scale" "1.3"
			}

			"100"
			{
				"hero_avg_level"	"70"
				
				"hp"		"8000"
				"mp"		"1000"
				"armor"		"28"
				"dmg_min"	"1400"
				"dmg_max"	"1500"
				"bat"		"0.3"
				"exp"		"440"
				"gold_min"	"600"
				"gold_max"	"700"
				"model_scale" "1.4"
			}
		}
		
		"beast"
		{
			"1"
			{
				"hero_avg_level"	"1"
				
				"hp"		"500"
				"mp"		"500"
				"armor"		"1"
				"dmg_min"	"31"
				"dmg_max"	"35"
				"bat"		"1.1"
				"exp"		"67"
				"gold_min"	"25"
				"gold_max"	"31"
				"model_scale" "0.7"
			}

			"5"
			{
				"hero_avg_level"	"4"
				
				"hp"		"750"
				"mp"		"500"
				"armor"		"3"
				"dmg_min"	"54"
				"dmg_max"	"58"
				"bat"		"1.1"
				"exp"		"70"
				"gold_min"	"35"
				"gold_max"	"55"
				"model_scale" "0.75"
			}

			"10"
			{
				"hero_avg_level"	"8"
				
				"hp"		"1000"
				"mp"		"500"
				"armor"		"4"
				"dmg_min"	"81"
				"dmg_max"	"85"
				"bat"		"1.1"
				"exp"		"80"
				"gold_min"	"60"
				"gold_max"	"85"
				"model_scale" "0.8"
			}

			"15"
			{	
				"hero_avg_level"	"10"
				
				"hp"		"2000"
				"mp"		"500"
				"armor"		"5"
				"dmg_min"	"240"
				"dmg_max"	"260"
				"bat"		"1.0"
				"exp"		"100"
				"gold_min"	"90"
				"gold_max"	"120"
				"model_scale" "0.85"
			}

			"20"
			{
				"hero_avg_level"	"15"
				
				"hp"		"3000"
				"mp"		"500"
				"armor"		"6"
				"dmg_min"	"300"
				"dmg_max"	"320"
				"bat"		"1.0"
				"exp"		"120"
				"gold_min"	"100"
				"gold_max"	"144"
				"model_scale" "0.9"
			}

			"25"
			{
				"hero_avg_level"	"20"
				
				"hp"		"4000"
				"mp"		"500"
				"armor"		"7"
				"dmg_min"	"320"
				"dmg_max"	"340"
				"bat"		"1.0"
				"exp"		"180"
				"gold_min"	"120"
				"gold_max"	"151"
				"model_scale" "1"
			}

			"40"
			{
				"hero_avg_level"	"35"
				
				"hp"		"5000"
				"mp"		"500"
				"armor"		"9"
				"dmg_min"	"420"
				"dmg_max"	"460"
				"bat"		"0.7"
				"exp"		"220"
				"gold_min"	"250"
				"gold_max"	"350"
				"model_scale" "1.1"
			}

			"60"
			{
				"hero_avg_level"	"50"
				
				"hp"		"6000"
				"mp"		"500"
				"armor"		"14"
				"dmg_min"	"580"
				"dmg_max"	"640"
				"bat"		"0.6"
				"exp"		"260"
				"gold_min"	"300"
				"gold_max"	"450"
				"model_scale" "1.2"
			}

			"80"
			{
				"hero_avg_level"	"60"
				
				"hp"		"7000"
				"mp"		"500"
				"armor"		"16"
				"dmg_min"	"830"
				"dmg_max"	"880"
				"bat"		"0.6"
				"exp"		"300"
				"gold_min"	"350"
				"gold_max"	"500"
				"model_scale" "1.3"
			}

			"100"
			{
				"hero_avg_level"	"70"
				
				"hp"		"8000"
				"mp"		"500"
				"armor"		"18"
				"dmg_min"	"1100"
				"dmg_max"	"1200"
				"bat"		"0.2"
				"exp"		"340"
				"gold_min"	"400"
				"gold_max"	"550"
				"model_scale" "1.4"
			}
		}
	}
}
