"root"
{
	"box_boss_possessed"
	{
		"type"		"garant_list"
		
		"items"
		{
			"item_possessed_sword"	"1"
		}
	}
	
	"box_neutral_items_tier1"
	{
		"type"		"uniform_list"

		"chance"	"20"

		"items"
		{
			"item_dust"				 	"1"
			"item_smoke_of_deceit"		"1"
			"item_enchanted_mango"		"1"
			"item_flask"				"1"
			"item_wraith_band" 			"1"
			"item_null_talisman" 		"1"
			"item_bracer" 				"1"
		}
	}

	"box_neutral_items_tier2"
	{
		"type"		"uniform_list"

		"chance"	"20"

		"items"
		{
			"item_ring_of_aquila"			  "1"
			"item_boots"				  "1"
			"item_gloves"			  "1"
			"item_belt_of_strength"			  "1"
			"item_robe"				  "1"
			"item_boots_of_elves"					  "1"
			"item_chainmail"		  "1"
			"item_bottle"				  "1"
			"item_ogre_axe" "1"
			"item_blade_of_alacrity" "1"
			"item_staff_of_wizardry" "1"
		}
	}

	"box_neutral_items_tier3"
	{
		"type"		"uniform_list"

		"chance"	"20"

		"items"
		{
			"item_power_treads"				  "1"
			"item_phase_boots"		  "1"
			"item_arcane_boots"			  "1"
			"item_soul_ring"				  "1"
			"item_vanguard"				  "1"
			"item_tome_un_3" "1"
			"item_tome_med" "1"
			"item_tome_str_3" "1"
			"item_tome_int_3" "1"
			"item_tome_agi_3" "1"
		}
	}

	"box_neutral_items_tier4"
	{
		"type"		"uniform_list"

		"chance"	"20"

		"items"
		{
			
			"item_sange"			  "1"
			"item_yasha"				  "1"
			"item_tome_str_6"				  "1"
			"item_tome_int_6"				  "1"
			"item_tome_agi_6"				  "1"
			"item_tome_un_6" "1"
	}
}
}
