"root"
{
	"target_mark_spawner_easy_1_radiant"
	{
		"type" 	"normal"
		
		"creeps"
		{
			"1" "npc_aac_creep_golem_radiant"
			"2" "npc_aac_creep_golem_radiant"
                        "3" "npc_aac_creep_golem_radiant"
                        "4" "npc_aac_creep_golem_radiant"

		}
	}
	"target_mark_spawner_easy_2_radiant"
	{
		"type" 	"normal"
		
		"creeps"
		{
			"1" "npc_aac_creep_golem_radiant"
			"2" "npc_aac_creep_golem_radiant"
			"3" "npc_aac_creep_golem_radiant"
			"4" "npc_aac_creep_golem_radiant"
		}
	}
	"target_mark_spawner_easy_3_radiant"
	{
		"type" 	"normal"
		
		"creeps"
		{
			"1" "npc_aac_creep_golem_radiant"
			"2" "npc_aac_creep_golem_radiant"
			"3" "npc_aac_creep_golem_radiant"
		}
	}
	"target_mark_spawner_easy_4_radiant"
	{
		"type" 	"normal"
		
		"creeps"
		{
			"1" "npc_aac_creep_golem_radiant"
			"2" "npc_aac_creep_golem_radiant"
			"3" "npc_aac_creep_golem_radiant"
		}
	}
	"target_mark_spawner_easy_5_radiant"
	{
		"type" 	"normal"
		
		"creeps"
		{
			"1" "npc_aac_creep_golem_radiant"
			"2" "npc_aac_creep_golem_radiant"
			"3" "npc_aac_creep_golem_radiant"
		}
	}
	"target_mark_spawner_medium_1_radiant"
	{
		"type" 	"beast"
		
		"creeps"
		{
			"1" "npc_aac_creep_centaur_radiant"
			"2" "npc_aac_creep_centaur_radiant"
			"3" "npc_aac_creep_centaur_radiant"
		}
	}
	"target_mark_spawner_hard_1_radiant"
	{
		"type" 	"ancient"
		
		"creeps"
		{
			"1" "npc_aac_creep_dragon_radiant"
			"2" "npc_aac_creep_dragon_radiant"
			"3" "npc_aac_creep_dragon_radiant"
			"4" "npc_aac_creep_dragon_radiant"
		}
	}
	"target_mark_spawner_easy_1_dire"
	{
		"type" 	"normal"
		
		"creeps"
		{
			"1" "npc_aac_creep_vulture_dire"
			"2" "npc_aac_creep_vulture_dire"
			"3" "npc_aac_creep_vulture_dire"
		}
	}
	"target_mark_spawner_easy_2_dire"
	{
		"type" 	"normal"
		
		"creeps"
		{
			"1" "npc_aac_creep_vulture_dire"
			"2" "npc_aac_creep_vulture_dire"
			"3" "npc_aac_creep_vulture_dire"
		}
	}
	"target_mark_spawner_easy_3_dire"
	{
		"type" 	"normal"
		
		"creeps"
		{
			"1" "npc_aac_creep_vulture_dire"
			"2" "npc_aac_creep_vulture_dire"
			"3" "npc_aac_creep_vulture_dire"
			"4" "npc_aac_creep_vulture_dire"
		}
	}
	"target_mark_spawner_easy_4_dire"
	{
		"type" 	"normal"
		
		"creeps"
		{
			"1" "npc_aac_creep_vulture_dire"
			"2" "npc_aac_creep_vulture_dire"
			"3" "npc_aac_creep_vulture_dire"
			"4" "npc_aac_creep_vulture_dire"
		}
	}
	"target_mark_spawner_easy_5_dire"
	{
		"type" 	"normal"
		
		"creeps"
		{
			"1" "npc_aac_creep_vulture_dire"
			"2" "npc_aac_creep_vulture_dire"
			"3" "npc_aac_creep_vulture_dire"
			"4" "npc_aac_creep_vulture_dire"
		}
	}
	"target_mark_spawner_medium_1_dire"
	{
		"type" 	"beast"
		
		"creeps"
		{
			"1" "npc_aac_creep_satyr_dire"
			"2" "npc_aac_creep_satyr_dire"
			"3" "npc_aac_creep_satyr_dire"
		}
	}
	"target_mark_spawner_hard_1_dire"
	{
		"type" 	"ancient"
		
		"creeps"
		{
			"1" "npc_aac_creep_dragon_dire"
			"2" "npc_aac_creep_dragon_dire"
			"3" "npc_aac_creep_dragon_dire"
			"4" "npc_aac_creep_dragon_dire"
		}
	}
}