print("[BATTLEARENA] addon_game_mode.lua loaded!")

if AngelArena == nil then
	AngelArena = class({})
end

require("util/init")
require('lib/timers')
require('lib/kv_preloaded_data')
require('util/custom_tables')
require('lib/hero_select')
require('lib/damage_to_exp_global')
require('lib/comeback_system')
require('lib/spawners/boss_spawner')
require('tp_s')
require('lib/spawners/creep_spawner')
require('lib/spawners/creep_leveling')
require('lib/spawners/scaling_camp')
require('lib/duel/duel_controller')
require('lib/solo/solo_mode')
require('lib/solo/solo_duel')
require('lib/move_limiter')
require('lib/runes/runes')
require('lib/utils')
require('lib/books')
require('lib/mana_pool')
require('lib/repick_item')
require('lib/hero_minimap_icons')
require('listeners/on_entity_killed')
require('listeners/on_npc_spawned')

require('filters/neutral_slot_filter')
require('filters/ultimate_gate_filter')
require('filters/gold')
require('game/gold_storage')
require('lib/stat_damage')
require('extensions/cdota_base_npc')
require('lib/augments/augments_core')
require('lib/augments/champions/champions')
require('lib/shop_extender')


-- РЎРїРёСЃРѕРє РјРѕРґСѓР»РµР№ РєРѕС‚РѕСЂС‹Рµ РЅСѓР¶РЅРѕ Р·Р°РіСЂСѓР¶Р°С‚СЊ РІ InitGameMode, Р° РЅРµ РїСЂРё СЃРѕР·РґР°РЅРёРё VM'РєРё 
local postRequireList = {
	'lib/base/player'
}

local Constants = require('consts') -- XP TABLE

function CEntityInstance:SetNetworkableEntityInfo(key, value)
    local t = CustomNetTables:GetTableValue("custom_entity_values", tostring(self:GetEntityIndex())) or {}
    t[key] = value
    CustomNetTables:SetTableValue("custom_entity_values", tostring(self:GetEntityIndex()), t)
end
function Precache( context )
	PrecacheResource("model", "models/heroes/enchantress/enchantress.vmdl", context)
	PrecacheResource("model", "models/heroes/omniknight/omniknight.vmdl", context)
	PrecacheResource("model", "models/heroes/doom/doom.vmdl", context)
	PrecacheResource("model", "models/items/doom/bringer_of_troubles_weapon/bringer_of_troubles_weapon.vmdl", context)
	PrecacheResource("model", "models/items/doom/bringer_of_troubles_head/bringer_of_troubles_head.vmdl", context)
	PrecacheResource("model", "models/items/doom/bringer_of_troubles_shoulder/bringer_of_troubles_shoulder.vmdl", context)
	PrecacheResource("model", "models/items/doom/bringer_of_troubles_back/bringer_of_troubles_back.vmdl", context)
	PrecacheResource("model", "models/items/doom/bringer_of_troubles_belt/bringer_of_troubles_belt.vmdl", context)
	PrecacheResource("model", "models/items/doom/bringer_of_troubles_tail/bringer_of_troubles_tail.vmdl", context)
	PrecacheResource("model", "models/items/doom/bringer_of_troubles_arms/bringer_of_troubles_arms.vmdl", context)
	PrecacheResource("model", "models/heroes/beastmaster/beastmaster.vmdl", context)
	PrecacheResource("model", "models/heroes/dark_seer/dark_seer.vmdl", context)
	PrecacheResource("model", "models/items/terrorblade/endless_purgatory_demon/endless_purgatory_demon.vmdl", context)
	PrecacheResource("model", "models/items/terrorblade/marauders_demon/marauders_demon.vmdl", context)
	-- РїРѕРґ-РјРѕРґРµР»Рё Р±РѕСЃСЃРѕРІ (head/cape/arms + РєРѕСЃРјРµС‚РёРєР°) вЂ” РёРЅР°С‡Рµ С‡Р°СЃС‚Рё РјРѕРґРµР»РµР№ РЅРµ Р·Р°РіСЂСѓР¶Р°СЋС‚СЃСЏ
	PrecacheResource("model", "models/heroes/omniknight/head.vmdl", context)
	PrecacheResource("model", "models/heroes/omniknight/cape.vmdl", context)
	PrecacheResource("model", "models/heroes/omniknight/bracer.vmdl", context)
	PrecacheResource("model", "models/items/omniknight/winged_helmet/winged_helmet.vmdl", context)
	PrecacheResource("model", "models/items/omniknight/guardofbasilius_weapon/guardofbasilius_weapon.vmdl", context)
	PrecacheResource("model", "models/heroes/beastmaster/beastmaster_arms.vmdl", context)
	PrecacheResource("model", "models/items/beastmaster/chimeras_anger_belt/chimeras_anger_belt.vmdl", context)
	PrecacheResource("model", "models/items/beastmaster/chimeras_anger_head/chimeras_anger_head.vmdl", context)
	PrecacheResource("model", "models/items/doom/eternal_fire_back/eternal_fire_back.vmdl", context)
	PrecacheResource("model", "models/items/doom/eternal_fire_belt/eternal_fire_belt.vmdl", context)
	PrecacheResource("model", "models/items/doom/eternal_fire_helmet/eternal_fire_helmet.vmdl", context)
	PrecacheResource("model", "models/items/doom/eternal_fire_shoulders/eternal_fire_shoulders.vmdl", context)
	PrecacheResource("model", "models/items/doom/fallen_sword/fallen_sword.vmdl", context)
	PrecacheResource("model", "models/items/enchantress/araceaes_tribute_skirt/araceaes_tribute_skirt.vmdl", context)
	PrecacheResource("model", "models/items/enchantress/enchantress_crown.vmdl", context)
	PrecacheResource("model", "models/items/enchantress/meadows_mercy/meadows_mercy.vmdl", context)
	PrecacheResource("model", "models/items/dark_seer/generals_mantle/generals_mantle.vmdl", context)
	PrecacheResource("model", "models/items/dark_seer/gombangdae_shoulder/gombangdae_shoulder.vmdl", context)
	PrecacheResource("model", "models/items/dark_seer/imperialrelics_back/imperialrelics_back.vmdl", context)
	PrecacheResource("model", "models/items/dark_seer/imperialrelics_belt/imperialrelics_belt.vmdl", context)
	PrecacheUnitByNameAsync("npc_ba_creep_golem_radiant", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_centaur_radiant", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_dragon_radiant", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_vulture_dire", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_satyr_dire", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_dragon_dire", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_golem_radiant_champion", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_centaur_radiant_champion", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_dragon_radiant_champion", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_vulture_dire_champion", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_satyr_dire_champion", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_creep_dragon_dire_champion", emptyFunc)
	PrecacheUnitByNameAsync("npc_aa_scaling_bear", emptyFunc)
	PrecacheResource("particle", "particles/life_catcher/life_catcher_out.vpcf", context)
	PrecacheResource("particle", "particles/life_catcher/life_catcher_in.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_visage/visage_soul_assumption_bolt.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_enchantress/enchantress_impetus.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis_base_attack.vpcf", context)
	PrecacheResource("particle", "particles/items_fx/blademail.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_centaur/centaur_warstomp.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_earthshaker/earthshaker_echoslam_start_c.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_snapfire/hero_snapfire_ultimate_linger.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_oracle/oracle_false_promise_dmg.vpcf", context)
	PrecacheResource("particle", "particles/ui_mouseactions/tower_range_indicator_alt_ground.vpcf", context)
	PrecacheResource("particle", "particles/ui_mouseactions/tower_range_indicator_alt_edge_sharp.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_batrider/batrider_flaming_lasso.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_lina/lina_spell_light_strike_array.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_doom_bringer/doom_bringer_doom_aura.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_doom_bringer/doom_bringer_doom_ring.vpcf", context)
	PrecacheResource("particle", "particles/econ/items/ogre_magi/ogre_magi_arcana/ogre_magi_arcana_stunned_orbit.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_tidehunter/tidehunter_krakenshell_purge.vpcf", context)
	PrecacheResource("particle", "particles/repick_zone/doom_bringer_doom_aura.vpcf", context)
	PrecacheResource("particle", "particles/items2_fx/radiance_owner.vpcf", context)
	PrecacheResource("particle", "particles/items2_fx/radiance.vpcf", context)
	PrecacheResource("particle", "particles/econ/events/ti9/radiance_owner_ti9.vpcf", context)
	PrecacheResource("particle", "particles/econ/events/ti9/radiance_ti9.vpcf", context)
	PrecacheResource("model", "models/heroes/lone_druid/spirit_bear.vmdl", context)
	PrecacheResource("model", "models/units/stegius/stegius.vmdl", context)
	PrecacheResource("model", "models/units/stegius/stegius.vmesh", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_stegius/desolus_wave.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_stegius/rage_of_desolus_buff.vpcf", context)
	PrecacheResource("model", "models/units/saber/saber.vmdl", context)
	PrecacheResource("model", "models/units/saber/saber.vmesh", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_saber/mana_burst_stack.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_saber/invisible_air.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_saber/excalibur.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_ember.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_ember_b.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_explosion.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_explosion_b.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_explosion_c.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_explosion_d.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_explosion_e.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_explosion_f.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_explosion_light.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_launch.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_launch_b.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_launch_smoke.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_skull.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_skull_lv.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_sphere_glow.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_sphere_glow_b.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_spirits_2.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_spirit_trail_b.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_spirit_trail_c.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_trail_d.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_trail_detail.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_trail_detail_b.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_trail_e.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_trail_f.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_trail_g.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_trail_h.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_trail_i.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_warmup.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_warmup_b.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_warmup_light.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_rage_of_arthas_warmup_smoke.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_skeletonking/alternative_vsolyanova_screen.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_stargazer/gamma_ray_immortal1.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_stargazer/gamma_ray_warp_blast_immortal1.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_stargazer/cosmic_countdown.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_mirratie/smoke_out_bomb.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_mirratie/impaling_shot.vpcf", context)
	PrecacheResource("particle", "particles/arena/units/heroes/hero_mirratie/impaling_shot_impale.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_projectile_fx.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_projectile_fx_b.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_projectile_fx_light.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_projectile_fx_sparkles.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_projectile_launch.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_projectile_launch_b.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_projectile_launch_old.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_projectile_wind.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_proj.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_proj_b.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_main.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_parent.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_child.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_child_glow.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_child_trail.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_flash.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_flash_b.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_model_collapse.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_model_catch.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_model_catch_sparkles.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_meepo/meepo_earthbind_model_catch_sparkles_b.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_faceless_void/faceless_void_backtrack.vpcf", context)
	PrecacheResource("particle", "particles/items_fx/blink_dagger_start.vpcf", context)
	PrecacheResource("particle", "particles/items_fx/blink_dagger_end.vpcf", context)
	PrecacheResource("model", "models/heroes/lanaya/lanaya.vmdl", context)
	-- MIRRATIE: Darkblade Adept (CC 2024, TA) — рантайм-пропы (см. modifier_mirratie_darkblade)
	PrecacheResource("model", "models/items/lanaya/templar_assasin_false_devotion_head/templar_assasin_false_devotion_head.vmdl", context)
	PrecacheResource("model", "models/items/lanaya/templar_assasin_false_devotion_shoulder/templar_assasin_false_devotion_shoulder.vmdl", context)
	PrecacheResource("model", "models/items/lanaya/templar_assasin_false_devotion_armor/templar_assasin_false_devotion_armor.vmdl", context)
	PrecacheResource("model", "models/items/lanaya/templar_assasin_false_devotion_weapon/templar_assasin_false_devotion_weapon.vmdl", context)
	PrecacheResource("particle", "particles/econ/items/templar_assassin/ta_2024_crownfall_cc/ta_cc_shoulder_ambient.vpcf", context)
	PrecacheResource("particle", "particles/econ/items/templar_assassin/ta_2024_crownfall_cc/ta_cc_shoulder_ambient_behind_glows.vpcf", context)
	PrecacheResource("particle", "particles/econ/items/templar_assassin/ta_2024_crownfall_cc/ta_cc_weapon_ambient.vpcf", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_riki.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_meepo.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_templar_assassin.vsndevts", context)
	PrecacheResource("particle", "particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis_transform.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis_ambient.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_phantom_assassin/phantom_assassin_crit_impact.vpcf", context)
	PrecacheResource("model", "models/heroes/terrorblade/demon.vmdl", context)
	PrecacheResource("model", "models/heroes/wraith_king/wraith_frost.vmdl", context)
	PrecacheResource("model", "models/heroes/necrolyte/necrolyte_skull.vmdl", context)
	PrecacheResource("model", "models/items/terrorblade/endless_purgatory_demon/endless_purgatory_demon.vmdl", context)
	PrecacheResource("soundfile", "soundevents/heroes/hero_saber.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/heroes/hero_arthas.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/heroes/hero_stargazer.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/bosses/duel_boss.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_juggernaut.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts", context)
	PrecacheResource("model", "models/heroes/kez/kez_base.vmdl", context)
	PrecacheResource("model", "models/heroes/ringmaster/ringmaster_base.vmdl", context)
	PrecacheResource("particle", "particles/creep_champion/creep_champion_status_effect.vpcf", context)
	PrecacheResource("particle", "particles/creep_champion_epic/creep_champion_epic_status_effect.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_leshrac/leshrac_split_earth.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_tiny/tiny_avalanche_lvl4.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_tiny/tiny_avalanche_projectile_lvl4.vpcf", context)
	PrecacheResource("particle", "particles/econ/items/leshrac/leshrac_tormented_staff/leshrac_split_tormented.vpcf", context)
	PrecacheResource("particle", "particles/econ/items/leshrac/leshrac_tormented_staff/leshrac_split_lightbeam_tormented.vpcf", context)
	PrecacheResource("particle", "particles/econ/items/antimage/antimage_weapon_basher_ti5/am_basher_manaburn_impact_lightning.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_elder_titan/elder_titan_earth_splitter.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_elder_titan/elder_titan_natural_order_physical.vpcf", context)
	PrecacheResource("particle", "particles/econ/items/underlord/underlord_ti8_immortal_weapon/underlord_ti8_immortal_pitofmalice_stun.vpcf", context)
	PrecacheResource("model", "models/heroes/warlock/warlock_demon.vmdl", context)
	PrecacheResource("model", "models/creeps/neutral_creeps/n_creep_ghost_b/n_creep_ghost_frost.vmdl", context)
	PrecacheUnitByNameAsync("npc_ba_minimap_champion_rare", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_minimap_champion_epic", emptyFunc)

	-- Soul Guardian
	PrecacheResource("particle", "particles/bosses/soul_guardian/soul_guardian_heroes_ring/soul_guardian_heroes_ring_1.vpcf", context)
	PrecacheResource("particle", "particles/bosses/soul_guardian/soul_guardian_heroes_ring/soul_guardian_heroes_ring_2.vpcf", context)
	PrecacheResource("particle", "particles/bosses/soul_guardian/soul_guardian_heavy_strike/econ/items/ursa/ursa_ti10/soul_guardian_heavy_strike.vpcf", context)
	PrecacheResource("particle", "particles/bosses/soul_guardian/soul_guardian_pure_heal/soul_guardian_pure_heal.vpcf", context)
	PrecacheResource("particle", "particles/bosses/soul_guardian/soul_guardian_damage_steal/soul_guardian_damage_steal_delay.vpcf", context)
	PrecacheResource("particle", "particles/bosses/soul_guardian/soul_guardian_damage_steal/soul_guardian_damage_steal.vpcf", context)
	PrecacheResource("particle", "particles/bosses/soul_guardian/soul_guardian_holy_rage/soul_guardian_holy_rage.vpcf", context)
	PrecacheResource("particle", "particles/shrine_restore_radiant/shrine_restore_radiant.vpcf", context)

	-- Duel bosses (solo mode): particles, models, units
	PrecacheResource("particle", "particles/range_finder_linear_1.vpcf", context)
	PrecacheResource("particle", "particles/range_finder_linear_2.vpcf", context)
	PrecacheResource("particle", "particles/magnataur_shockwave_red.vpcf", context)
	PrecacheResource("particle", "particles/magnataur_shockwave_cracks_glow_red.vpcf", context)
	PrecacheResource("particle", "particles/magnataur_shockwave_cracks_warp_red.vpcf", context)
	PrecacheResource("particle", "particles/magnataur_shockwave_glow_red.vpcf", context)
	PrecacheResource("particle", "particles/magnataur_shockwave_light_red.vpcf", context)
	PrecacheResource("particle", "particles/magnataur_shockwave_sparks_red.vpcf", context)
	PrecacheResource("particle", "particles/primal_beast_rock_throw_arc.vpcf", context)
	PrecacheResource("particle", "particles/primal_beast_rock_throw_arc_b.vpcf", context)
	PrecacheResource("particle", "particles/monster/ability_warning_ring.vpcf", context)
	PrecacheResource("particle", "particles/monster/ability_warning_ring_b.vpcf", context)
	PrecacheResource("particle", "particles/monster/ability_warning_ring_c.vpcf", context)
	PrecacheResource("particle", "particles/generic_stunned.vpcf", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_primal_beast.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_spirit_breaker.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_tidehunter.vsndevts", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001_red.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001a.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001b.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001c.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001d.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001e.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001i.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001i0.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001j.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001k.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001l.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001m.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001n.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001o.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001o0.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001o1.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001o2.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001o3.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001o4.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001o5.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001p.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001s.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001t.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001t0.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001t1.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001t2.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001t3.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001t4.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001t5.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001t6.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001t7.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001t8.vpcf", context)
	PrecacheResource("particle", "particles/boss/bs/ability_001u.vpcf", context)
	PrecacheResource("model", "models/heroes/primal_beast/primal_beast_base.vmdl", context)
	PrecacheResource("model", "models/items/lycan/ultimate/frostivus2018_lycan_savage_beast_form/frostivus2018_lycan_savage_beast_form.vmdl", context)
	PrecacheUnitByNameAsync("npc_ba_duel_boss_01", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_duel_hound", emptyFunc)

	-- Duel boss 02 «Воин Пустоши» (skull_warrior)
	PrecacheResource("model", "models/monsters/monster00007/monster00007.vmdl", context)
	PrecacheResource("model", "models/creeps/neutral_creeps/n_creep_centaur_med/n_creep_centaur_med.vmdl", context)
	PrecacheResource("particle", "particles/unit/elite_032.vpcf", context)
	PrecacheResource("particle", "particles/unit/elite_040.vpcf", context)
	PrecacheResource("particle", "particles/unit/elite_042.vpcf", context)
	PrecacheResource("particle", "particles/unit/elite_042units/heroes/hero_mars/elite_042a.vpcf", context)
	PrecacheResource("particle", "particles/unit/elite_042units/heroes/hero_mars/elite_042b.vpcf", context)
	PrecacheResource("particle", "particles/unit/elite_042units/heroes/hero_mars/elite_042c.vpcf", context)
	PrecacheResource("particle", "particles/unit/elite_042units/heroes/hero_mars/elite_042d.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_dawnbreaker/dawnbreaker_elated_fury_landing_dust.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_primal_beast/primal_beast_pulverize_hit.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_primal_beast/primal_beast_rock_throw_impact.vpcf", context)
	PrecacheResource("particle", "particles/econ/items/earthshaker/deep_magma/deep_magma_10th/deep_magma_10th_echoslam_start.vpcf", context)
	PrecacheResource("particle", "particles/items2_fx/ward_die_generic_sentry.vpcf", context)
	PrecacheResource("particle", "particles/killstreak/killstreak_ti10_hud_lv2.vpcf", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_slardar.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_mars.vsndevts", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_magnataur.vsndevts", context)
	PrecacheUnitByNameAsync("npc_ba_duel_boss_02", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_duel_skull_miner", emptyFunc)

	-- Duel boss 03 «Deadeye» kit v3 (дальний стрелок, модель Снайпера + сет Blacksail Cannoneer)
	PrecacheResource("model", "models/heroes/sniper/sniper.vmdl", context)
	PrecacheResource("model", "models/items/sniper/sniper_black_sails_cannoneer_head_2/sniper_black_sails_cannoneer_head_2.vmdl", context)
	PrecacheResource("model", "models/items/sniper/sniper_black_sails_cannoneer_shoulder/sniper_black_sails_cannoneer_shoulder.vmdl", context)
	PrecacheResource("model", "models/items/sniper/sniper_black_sails_cannoneer_back/sniper_black_sails_cannoneer_back.vmdl", context)
	PrecacheResource("model", "models/items/sniper/sniper_black_sails_cannoneer_arms/sniper_black_sails_cannoneer_arms.vmdl", context)
	PrecacheResource("model", "models/items/sniper/sniper_black_sails_cannoneer_weapon/sniper_black_sails_cannoneer_weapon.vmdl", context)
	PrecacheResource("model", "models/heroes/rattletrap/rattletrap_cog.vmdl", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_base_attack.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_base_attack_explosion_flash.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_crosshair.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_dust_hit.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_take_aim_overhead.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_shrapnel_impacts.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_shard_concussive_grenade_model.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_shard_concussive_grenade_impact_burst.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_sniper/sniper_shard_concussive_grenade_impact_smoke.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_rattletrap/rattletrap_hookshot.vpcf", context)
	PrecacheResource("particle", "particles/units/heroes/hero_rattletrap/rattletrap_cog_deploy.vpcf", context)
	PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_rattletrap.vsndevts", context)
	PrecacheUnitByNameAsync("npc_ba_duel_boss_03", emptyFunc)
	PrecacheUnitByNameAsync("npc_ba_duel_cog", emptyFunc)

end

function Activate()
    print( "AngelArena Activate start." )
	GameRules.AngelArena = AngelArena()
	GameRules.AngelArena:InitGameMode()
end

function AngelArena:InitGameMode()
	print( "AngelArena InitGameMode start." )

	SoloMode:Init()
	SoloDuel:Init()
	
	for _, moduleName in pairs(postRequireList) do
		require(moduleName)
	end
	GameRules:SetTimeOfDay(0.25)
    GameRules:SetCustomGameSetupAutoLaunchDelay(0)
    GameRules:SetHeroSelectPenaltyTime(0)
    GameRules:SetPreGameTime(5)
    GameRules:SetHeroSelectionTime(9999999)
    GameRules:SetShowcaseTime(0)
    GameRules:SetStrategyTime(5)
    GameRules:SetPostGameTime(0)
	GameRules:SetUseUniversalShopMode(true)
    GameRules:GetGameModeEntity():SetFreeCourierModeEnabled(true)
	GameRules:SetGoldPerTick(2.5)
	GameRules:SetSameHeroSelectionEnabled(true)

	GameRules:SetHeroRespawnEnabled(true)
	GameRules:SetGoldTickTime(1)
	GameRules:SetTreeRegrowTime(40)
	GameRules:SetUseBaseGoldBountyOnHeroes(true)
	GameRules:GetGameModeEntity():SetPauseEnabled(false) -- solo-lobby auto-pause on focus loss would freeze timers
print("[BATTLEARENA] addon_game_mode.lua loaded!")


	local GameMode = GameRules:GetGameModeEntity()
	Convars:SetInt("dota_max_physical_items_purchase_limit", 10000)
	GameMode:SetBountyRuneSpawnInterval(120.0)
	GameMode:SetFixedRespawnTime(45)
	GameMode:SetCameraDistanceOverride(1440)
	GameMode:SetNeutralStashEnabled(false)
	GameMode:SetHUDVisible(11, false) -- DOTA_HUD_VISIBILITY_INVENTORY_GOLD: hide default gold display
	for i = 0, 11 do
		GameMode:SetRuneEnabled(i, true)
	end
	
	GameMode:SetCustomXPRequiredToReachNextLevel(Constants.XP_PER_LEVEL_TABLE)
	GameMode:SetUseCustomHeroLevels(true)

	--Init listeners
	ListenToGameEvent('game_rules_state_change', Dynamic_Wrap(AngelArena, 'OnGameRulesStateChange'), self)
	ListenToGameEvent('dota_rune_activated_server', function(context, event) return Runes:OnRuneActivate(event); end, {})
	ListenToGameEvent("entity_killed", Dynamic_Wrap(OnEntityKilledListener, "OnEntityKilled"), {})
	ListenToGameEvent('npc_spawned', Dynamic_Wrap(OnNPCSpawnedListener, "OnNPCSpawned"), {})
	
	-- hero pick: player connect hook (replaces wod's RegisterLoadListener)
	local function OnPlayerConnected(_, event)
		local pid = event.playerid
		if pid == nil then return end
		if hero_select then
			hero_select:PlayerConnected({PlayerID = pid})
		end
		if CustomTables then
			CustomTables:OnRequestCustomTables({PlayerID = pid})
		end
		if SoloMode then
			SoloMode:OnPlayerConnected(pid)
		end
	end
	ListenToGameEvent("player_connect_full", OnPlayerConnected, {})
	for i = 0, DOTA_MAX_TEAM_PLAYERS - 1 do
		if PlayerResource:IsValidTeamPlayerID(i) then
			OnPlayerConnected(nil, {playerid = i})
		end
	end

	-- hero pick: register the roster and abilities for the custom pick screen
	hero_select:RegisterHeroes()
	
-- Stegius: удары иллюзий героя снижают броню врагу от имени героя.
-- Механизм — модификатор-пассивка с MODIFIER_EVENT_ON_ATTACK (heroes/hero_stegius/desolating_touch.lua),
-- который иллюзии наследуют от героя. DamageFilter-дубль удалён 2026-08-09 (крашился
-- на GetIllusionSource + давал бы двойные стаки).
	
	--################################## BASE MODIFIERS ############################################### --
	LinkLuaModifier("modifier_full_disable_stun", 'modifiers/modifier_full_disable_stun', LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_hidden_from_map", 'modifiers/modifier_hidden_from_map', LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_dissapear", 'modifiers/modifier_dissapear', LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stop", 'modifiers/modifier_stop', LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_medical_tractate", 'modifiers/modifier_medical_tractate', LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_godmode", 'modifiers/modifier_godmode', LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_courier", 'modifiers/modifier_courier', LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_override_magic_resist", 'modifiers/modifier_override_magic_resist', LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_spell_amp_from_int", 'modifiers/modifier_spell_amp_from_int', LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_magical_resistance", 'modifiers/modifier_magical_resistance', LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_doom_litany_cosmetics", "modifiers/modifier_doom_litany_cosmetics", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_pregame_stunned", "game/modifiers/modifier_pregame_stunned", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_augment_overrider", "game/modifiers/modifier_augment_overrider", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_augment_primary_reader", "lib/augments/modifier_augment_primary_reader", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_ba_champion", "lib/augments/champions/modifier_ba_champion", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_augment_summon_health", "lib/augments/modifier_augment_summon_health", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stegius_desolating_touch_debuff", "heroes/hero_stegius/desolating_touch", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stegius_desolating_touch", "heroes/hero_stegius/desolating_touch", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stegius_talent_stats", "heroes/hero_stegius/desolating_touch", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stegius_brightness_of_desolate", "heroes/hero_stegius/brightness_of_desolate", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stegius_brightness_of_desolate_effect", "heroes/hero_stegius/brightness_of_desolate", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stegius_brightness_of_desolate_damage", "heroes/hero_stegius/brightness_of_desolate", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stegius_brightness_of_desolate_steal_buff", "heroes/hero_stegius/brightness_of_desolate", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_saber_mana_burst", "heroes/hero_saber/mana_burst", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_saber_mana_burst_active", "heroes/hero_saber/mana_burst", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_saber_instinct", "heroes/hero_saber/instinct", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_saber_invisible_air", "heroes/hero_saber/invisible_air", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_saber_avalon", "heroes/hero_saber/avalon", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_saber_avalon_invulnerability", "heroes/hero_saber/avalon", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_arthas_vsolyanova_active", "heroes/hero_arthas/modifier_arthas_vsolyanova_active", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_arthas_talent_stats", "heroes/hero_arthas/modifier_arthas_talent_stats", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stargazer_inverse_field", "heroes/hero_stargazer/inverse_field", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stargazer_cosmic_countdown", "heroes/hero_stargazer/cosmic_countdown", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_stargazer_talent_stats", "heroes/hero_stargazer/modifier_stargazer_talent_stats", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_mirratie_smoke_out_cloud", "heroes/hero_mirratie/smoke_out", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_mirratie_smoke_out_debuff", "heroes/hero_mirratie/smoke_out", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_mirratie_snagshot_flight", "heroes/hero_mirratie/snagshot", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_mirratie_sixth_sense_dodge", "heroes/hero_mirratie/sixth_sense", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_mirratie_darkblade", "heroes/hero_mirratie/modifier_mirratie_darkblade", LUA_MODIFIER_MOTION_NONE)

	--#################################### DUEL BOSSES (solo mode) #################################### --
	LinkLuaModifier("modifier_duel_boss_cast_protection", "lib/duel_bosses/modifiers/modifier_duel_boss_cast", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_busy", "lib/duel_bosses/modifiers/modifier_duel_boss_cast", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_phase_window", "lib/duel_bosses/modifiers/modifier_duel_boss_phase", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_phase_buff", "lib/duel_bosses/modifiers/modifier_duel_boss_phase", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_summon_protect", "lib/duel_bosses/modifiers/modifier_duel_boss_summon_protect", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_dummy", "lib/duel_bosses/modifiers/modifier_duel_boss_dummy", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_stagger", "lib/duel_bosses/modifiers/modifier_duel_boss_stagger", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_frame", "lib/duel_bosses/modifiers/modifier_duel_boss_frame", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_avalanche", "lib/duel_bosses/modifiers/modifier_duel_boss_avalanche", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_upheaval_zone", "lib/duel_bosses/modifiers/modifier_duel_boss_upheaval", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_upheaval", "lib/duel_bosses/modifiers/modifier_duel_boss_upheaval", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_skull_arena_zone", "lib/duel_bosses/modifiers/modifier_duel_boss_skull_arena", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_skull_arena_boundary", "lib/duel_bosses/modifiers/modifier_duel_boss_skull_arena", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_skull_arena_buff", "lib/duel_bosses/modifiers/modifier_duel_boss_skull_arena", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_duel_boss_smoke", "lib/duel_bosses/modifiers/modifier_duel_boss_smoke", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_deadeye_trance", "creeps/duel_bosses/deadeye/deadeye_phase", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_deadeye_cog", "abilities/deadeye_cog_passive", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_deadeye_cog_stick", "abilities/deadeye_cog_passive", LUA_MODIFIER_MOTION_NONE)
	
	--########################################## FILTERS ############################################### --
	GameMode:SetRuneSpawnFilter(function(context, event) return Runes:ModifierRuneSpawn(event); end, {})
	GameMode:SetItemAddedToInventoryFilter(function(context, event) return NeutralSlotFilter:ItemAddedToInventoryFilter(event) end, {})
	GameMode:SetExecuteOrderFilter(function(context, event)
		if not NeutralSlotFilter:ExecuteOrderFilter(event) then return false end
		if not UltimateGateFilter:ExecuteOrderFilter(event) then return false end
		if not ManaPool:BlockCastOrder(event) then return false end
		return true
	end, {})
	GameMode:SetModifyGoldFilter(function(context, event) return GoldFilter:ModifyGoldFilter(event); end, {})
	GameMode:SetBountyRunePickupFilter(function(context, event) return GoldFilter:BountyRuneFilter(event); end, {})
	GameMode:SetDamageFilter(function(context, event)
		return StatDamage:DamageFilter(event)
	end, {})
	
	print("All modifiers linked")

	CreepSpawner:Init()
	CreepSpawner:RegisterOnSpawnCallback(function(arg) CreepLeveling:OnSpawnCallback(arg); end)
	CreepSpawner:RegisterOnDeathCallback(function(arg) CreepLeveling:OnDeathCallback(arg); end)
	
	BossSpawner:Init()
	ScalingCamp:Init()
	GoldStorage:Init()
	Champions:Init()
	ManaPool:Init()
	-- HeroMinimapIcons:Init() — ОТКЛЮЧЕНО 2026-08-12: движковая иконка
	-- кастомного героя рисуется штатно (mod_textures.txt + перекрытый лист
	-- minimap_hero_sheet_psd_3529892a.vtex_c, см. AGENTS.md); оверлей не нужен.
	-- HeroMinimapIcons:Init()
end


function AngelArena:OnGameInProgress(event)
    print("event on game start")
	CreepSpawner:StartSpawning()
	BossSpawner:StartSpawning()
	ScalingCamp:StartSpawning()
	Champions:Start()
	
	local heroes = HeroList:GetAllHeroes()
	for _, hero in pairs(heroes) do
		if hero and hero:IsRealHero() then
			print("IsRealHero")
			hero:AddNewModifier(nil, nil, "modifier_magical_resistance", {duration = -1})
		end
	end

end

function AngelArena:OnGameRulesStateChange(event)
    local newState = GameRules:State_Get()
    print("[GAMESTATE] Changed to: " .. newState)
    if newState == DOTA_GAMERULES_STATE_HERO_SELECTION then
        hero_select:init()
    end
    if newState == DOTA_GAMERULES_STATE_PRE_GAME then
        hero_select:EndPick()
		if SoloMode then SoloMode:ForceAllToRadiant() end
        CustomGameEventManager:Send_ServerToAllClients("show_beta_notice", {})
    end
    if newState == DOTA_GAMERULES_STATE_GAME_IN_PROGRESS then
        print("[GAMESTATE] -> GAME_IN_PROGRESS detected")
        print("Game time: ", GameRules:GetGameTime())
		if SoloMode then SoloMode:ForceAllToRadiant() end
		DuelController:OnGameStart()
		AngelArena:OnGameInProgress(event)
	end
end